// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables with fallbacks for development
const getEnvVar = (key: string, isRequired = true): string => {
  const value = import.meta.env[key];
  
  if (isRequired && (value === undefined || value === '')) {
    console.error(`Missing required environment variable: ${key}`);
    if (import.meta.env.DEV) {
      console.warn('Running in development mode with missing Supabase credentials');
      // Return empty string in development to prevent immediate crash
      return '';
    }
    throw new Error(`Missing required environment variable: ${key}`);
  }
  
  return value || '';
};

const SUPABASE_URL = getEnvVar('VITE_SUPABASE_URL');
const SUPABASE_ANON_KEY = getEnvVar('VITE_SUPABASE_ANON_KEY') || getEnvVar('VITE_SUPABASE_PUBLISHABLE_KEY');
const SUPABASE_SERVICE_ROLE_KEY = getEnvVar('VITE_SUPABASE_SERVICE_ROLE_KEY', false);

// Only validate in production or if we have values
const shouldValidate = import.meta.env.PROD || (SUPABASE_URL && SUPABASE_ANON_KEY);

if (shouldValidate && (!SUPABASE_URL || !SUPABASE_ANON_KEY)) {
  const errorMsg = 'Missing required Supabase environment variables. ' +
    'Please check your .env file and ensure all required variables are set.';
  console.error(errorMsg);
  if (import.meta.env.PROD) {
    throw new Error(errorMsg);
  }
}

/**
 * Regular Supabase client for client-side usage.
 * This client respects Row Level Security (RLS) policies.
 */
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);

/**
 * Admin Supabase client with service role access.
 * WARNING: This client bypasses Row Level Security (RLS) policies.
 * Only use for server-side operations that require elevated privileges.
 */
export const supabaseAdmin = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  }
);

// Type for the admin client
export type SupabaseAdminClient = typeof supabaseAdmin;

// Helper function to get the admin client
// Use this function to ensure proper typing and error handling
export const getAdminClient = (): SupabaseAdminClient | null => {
  try {
    const serviceRoleKey = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY;
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;

    if (!supabaseUrl || !serviceRoleKey) {
      console.error('Missing Supabase URL or Service Role Key');
      console.log('Current env:', {
        hasUrl: !!supabaseUrl,
        hasKey: !!serviceRoleKey,
        keyPrefix: serviceRoleKey?.substring(0, 5) + '...'
      });
      return null;
    }

    console.log('Creating admin client with URL:', supabaseUrl);
    const client = createClient<Database>(supabaseUrl, serviceRoleKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
        detectSessionInUrl: false
      }
    });

    // Test the connection
    client.from('staff').select('id').limit(1).then(
      () => console.log('Admin client connected successfully'),
      (err) => console.error('Admin client connection test failed:', err)
    );

    return client;
  } catch (error) {
    console.error('Error creating admin client:', error);
    return null;
  }
};